version: '3'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
  webtechno-db:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: socialdb
    ports:
      - 27017:27017
  webtechno-backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    environment:
      PORT: 8080
      MONGODB_URI: mongodb://webtechno-db:27017/socialdb
    ports:
      - 8080:8080
  webtechno-frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    environment:
      PORT: 3000
      PROXY_API: http://webtechno-backend:8080/
    ports:
      - 3000:3000
