version: '3'
services:
  nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
  db:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./dump:/dump
      - ./mongorestore.sh:/docker-entrypoint-initdb.d/mongorestore.sh
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    environment:
      PORT: 8080
      MONGODB_URI: mongodb://db:27017/social
      FRONTEND_URL: http://nginx:80
    ports:
      - 8080:8080
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    environment:
      PORT: 3000
      API_HOST: http://webtechno-backend:8080
    ports:
      - 3000:3000
