version: '3'
services:
  db:
    image: mongo:latest
    command: mongod --quiet --logpath /dev/null
    ports:
      - 27017:27017
    volumes:
      - ./dump:/dump
      - ./mongorestore.sh:/docker-entrypoint-initdb.d/mongorestore.sh
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    environment:
      - PORT=8080
      - MONGODB_URI=mongodb://db:27017/social
      - FRONTEND_URL=https://frontend
    ports:
      - 8080:8080
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    environment:
      - PORT=80
      - PROXY_API=http://backend:8080
      - API_HOST=https://frontend:8080/api
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./frontend/nginx/conf:/etc/nginx/conf.d/:ro
      - ./frontend/certbot/www:/var/www/certbot/:ro
      - ./frontend/certbot/conf:/etc/nginx/ssl/:ro
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./frontend/certbot/www:/var/www/certbot/:rw
      - ./frontend/certbot/conf:/etc/letsencrypt/:rw
